version: '3.8'

services:
  backend:
    image: $DOCKER_USERNAME/bobapp-back
    build:
      context: ./back
    ports:
      - "8080:8080"
    networks:
      - bobapp-network

  frontend:
    image: $DOCKER_USERNAME/bobapp-front
    build:
      context: ./front
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - bobapp-network

networks:
  bobapp-network:
    driver: bridge
