name: CI/CD - Tests et Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Tests et couverture - Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installation des dépendances Maven
        run: mvn clean install
        working-directory: back

      - name: Exécution des tests avec JaCoCo
        run: mvn test jacoco:report
        working-directory: back

      - name: Upload du rapport de couverture JaCoCo
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/

  frontend-tests:
    name: Tests et couverture - Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installation des dépendances
        run: npm install
        working-directory: front

      - name: Exécution des tests avec couverture
        run: ng test --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: front

      - name: Upload du rapport de couverture Angular
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage-report
          path: front/coverage/
