name: Analyse qualité avec SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: Analyse SonarQube
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

          
      # - name: Installation de Java & Maven
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'

      # - name: Installation de Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'

      # - name: Installation des dépendances Angular
      #   run: npm install
      #   working-directory: front

      # - name: Exécution des tests Angular (avec couverture)
      #   run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
      #   working-directory: front

      # - name: Compilation du back-end avec Maven
      #   run: mvn clean verify
      #   working-directory: back

      # - name: Analyse SonarQube
      #   run: mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      #   working-directory: back
